config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :contacts, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :company
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :addresses
  has_many :workplaces
  has_many :contacts, through: :workplaces
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :workplaces
  has_many :companies, through: :workplaces

  geocoded_by :address
  after_validation :geocode, if: :address_one_changed?


  def address
  [address_one, zipcode, country].compact.join(', ')
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workplace.rb
class Workplace < ApplicationRecord
  belongs_to :contact
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def show
    @contact = Contact.find(params[:id])
    @hash = Gmaps4rails.build_markers(@contact) do |contact, marker|
      marker.lat contact.latitude
      marker.lng contact.longitude
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/show.html.erb
<div class="upper-banner">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <h1>Gestion des contacts</h1>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8">

      <!-- profile_summary -->
      <div class="row">
        <div class="col-xs-3 text-right">
          <%= image_tag @contact.profile_pic_url, class: "avatar-large" %>
        </div>

        <div class="col-xs-9">
          <div class="contact-details">
            <h3><%= @contact.first_name %> <%= @contact.part %> <%= @contact.last_name %></h3>
            <h4>Web developper @<strong>Smartexpat</strong></h4>
            <h5><i class="fa fa-envelope" aria-hidden="true"></i> <%= link_to @contact.email, "mailto:"+@contact.email %> | <i class="fa fa-mobile" aria-hidden="true"></i> <%= @contact.mobile %></h5>
            <h5><i class="fa fa-linkedin-square" aria-hidden="true"></i> <%= link_to @contact.linkedin, @contact.linkedin, target: "_blank" %></h5>
          </div>
        </div>

      </div>

      <!-- tabs -->
      <div class="row">
        <div class="col-xs-12">
          <div class="tabs">
            <a class="tab active" data-target="#tab-pro">
              <p>Informations</p>
              <h3>professionnelles</h3>
            </a>
            <a class="tab" data-target="#tab-perso">
              <p>Informations</p>
              <h3>personnelles</h3>
            </a>
          </div>
        </div>
      </div>

      <!-- tab pro -->
      <div class="row tab-content" id="tab-pro">
        <div class="col-xs-12">
          <p>Infos pro</p>
        </div>
      </div>

      <!-- tab perso -->
      <div class="row tab-content hidden" id="tab-perso">
        <div class="col-xs-12">
          <div class="col-xs-6">
            <p><strong>Date de naissance :</strong> <%= @contact.date_of_birth.strftime("%d/%m/%Y")%> <em>(<%= (DateTime.now - @contact.date_of_birth).to_i / 365 %> ans)</em> </p>
            <p><%= @contact.address_one %></p>
            <p><%= @contact.address_two %></p>
            <p><%= @contact.zipcode %> <%= @contact.city.capitalize %> - <%= @contact.country.capitalize %></p>
          </div>
          <div class="col-xs-6">
            <!-- The map will be drawn in this div -->
              <div id="map" style="width: 100%; height: 600px;"></div>
          </div>
        </div>
      </div>

    </div>
    <div class="col-sm-4"></div>
  </div>
</div>

<% content_for(:after_js) do %>
    <%= javascript_tag do %>
        $(function(){
          $(".tab").on("click", function(e){
            <!-- // Change active tab -->
            $(".tab").removeClass('active');
            $(this).addClass('active');
            <!-- // Hide all tab-content (use class="hidden") -->
            $(".tab-content").addClass('hidden');
            <!-- // Show target tab-content (use class="hidden") -->
            $($(this).data('target')).removeClass('hidden');

          });

        });
      <% end %>
<% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers([
          {
            "lat": <% @contact.latitude %>,
            "lng": <% @contact.longitude %>
          };
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'shared/navbar' %>
    <% end %>
    <div class="main-content">
      <%= render 'shared/flashes' %>
    <%= yield %>
    </div>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js)  %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to authenticated_root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>